all: data/dicoms.col

data/dicoms.col:
	@rm -f $@
	find data/train/ data/validate/ -name \*.dcm -print0 | sort -z | PYTHONPATH=generated/python:python/.libs xargs -0 scripts/load-dicom.py --output-path=$@
